/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/chernovan_nemesis/scene.gltf -t -r public
Author: Swiss_Fox (https://sketchfab.com/Swiss_Fox)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/chernovan-nemesis-c6c91c73e93444f4b72d6c24db778e73
Title: Chernovan Nemesis
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    GearHatchRL_Cube_027_HullInside_0: THREE.Mesh
    GearHatchRL_Cube_027_Hull_0: THREE.Mesh
    GearHatchLR_Cube_026_HullInside_0: THREE.Mesh
    GearHatchLR_Cube_026_Hull_0: THREE.Mesh
    GearHatchLL_Cube_025_HullInside_0: THREE.Mesh
    GearHatchLL_Cube_025_Hull_0: THREE.Mesh
    GearHatchRR_Cube_024_HullInside_0: THREE.Mesh
    GearHatchRR_Cube_024_Hull_0: THREE.Mesh
    GearWheelsRear_Cube_023_LandingGear_0: THREE.Mesh
    GearWheelsRear_Cube_023_Wheel_0: THREE.Mesh
    GearPiston_Cube_022_LandingGear_0: THREE.Mesh
    Instruments_Cockpit_Cube_000_Instruments_0: THREE.Mesh
    CanopyOpenable_Cube_019_Glass_0: THREE.Mesh
    CanopyOpenable_Cube_019_Canopy_0: THREE.Mesh
    FanR_Cube_018_VTolFan_0: THREE.Mesh
    FanL_Cube_016_VTolFan_0: THREE.Mesh
    EngineNozzleR_Cube_015_Black_0: THREE.Mesh
    EngineNozzleR_Cube_015_Engine_0: THREE.Mesh
    EngineNozzleL_Cube_013_Black_0: THREE.Mesh
    EngineNozzleL_Cube_013_Engine_0: THREE.Mesh
    GearFront_Cube_012_LandingGear_0: THREE.Mesh
    GearFront_Cube_012_HullInside_0: THREE.Mesh
    GearFront_Cube_012_Hull_0: THREE.Mesh
    GearFront_Cube_012_Wheel_0: THREE.Mesh
    Hatch2_2R_Cube_011_HullInside_0: THREE.Mesh
    Hatch2_2R_Cube_011_Hull_0: THREE.Mesh
    Hatch2_2L_Cube_010_HullInside_0: THREE.Mesh
    Hatch2_2L_Cube_010_Hull_0: THREE.Mesh
    Hatch2R_Cube_009_HullInside_0: THREE.Mesh
    Hatch2R_Cube_009_Hull_0: THREE.Mesh
    Hatch2L_Cube_008_HullInside_0: THREE.Mesh
    Hatch2L_Cube_008_Hull_0: THREE.Mesh
    Hatch1_2R_Cube_006_HullInside_0: THREE.Mesh
    Hatch1_2R_Cube_006_Hull_0: THREE.Mesh
    Hatch1_2L_Cube_005_HullInside_0: THREE.Mesh
    Hatch1_2L_Cube_005_Hull_0: THREE.Mesh
    Hatch1R_Cube_004_HullInside_0: THREE.Mesh
    Hatch1R_Cube_004_Hull_0: THREE.Mesh
    Hatch1L_Cube_002_HullInside_0: THREE.Mesh
    Hatch1L_Cube_002_Hull_0: THREE.Mesh
    Cockpit_Cube_001_SeatStoff_0: THREE.Mesh
    Cockpit_Cube_001_Cockpit_0: THREE.Mesh
    Black_Cube_000_Black_0: THREE.Mesh
    Glass_Cube_021_Glass_0: THREE.Mesh
    Nemesis_Cube_014_HullInside_0: THREE.Mesh
    Nemesis_Cube_014_Hull_0: THREE.Mesh
    Nemesis_Cube_014_Cannon_0: THREE.Mesh
    Nemesis_Cube_014_Engine_0: THREE.Mesh
    Nemesis_Cube_014_Canopy_0: THREE.Mesh
  }
  materials: {
    HullInside: THREE.MeshStandardMaterial
    Hull: THREE.MeshPhysicalMaterial
    LandingGear: THREE.MeshStandardMaterial
    Wheel: THREE.MeshStandardMaterial
    Instruments: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    Canopy: THREE.MeshPhysicalMaterial
    VTolFan: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Engine: THREE.MeshStandardMaterial
    SeatStoff: THREE.MeshStandardMaterial
    Cockpit: THREE.MeshStandardMaterial
    Cannon: THREE.MeshStandardMaterial
  }
}

type ActionName = 'TakeOff / Flying'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/chernovan_nemesis/scene.gltf') as GLTFResult
  const { actions, names } = useAnimations(animations, group)
  useEffect(() => {
    actions[names[0]]?.reset().fadeIn(0.3).play()
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="Chernovan_Nemesisfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="NemesisExport_obj" position={[0, 13.79, 1.22]} rotation={[-0.07, 0, 0]}>
                  <group name="GearPiston_Cube_022" position={[0, 28.54, -8.4]}>
                    <group name="GearHatchRL_Cube_027" position={[-185.46, -0.19, -47.95]} rotation={[-0.26, 0, 0]}>
                      <mesh name="GearHatchRL_Cube_027_HullInside_0" geometry={nodes.GearHatchRL_Cube_027_HullInside_0.geometry} material={materials.HullInside} />
                      <mesh name="GearHatchRL_Cube_027_Hull_0" geometry={nodes.GearHatchRL_Cube_027_Hull_0.geometry} material={materials.Hull} />
                    </group>
                    <group name="GearHatchLR_Cube_026" position={[185.45, -0.19, -47.95]} rotation={[-0.26, 0, 0]}>
                      <mesh name="GearHatchLR_Cube_026_HullInside_0" geometry={nodes.GearHatchLR_Cube_026_HullInside_0.geometry} material={materials.HullInside} />
                      <mesh name="GearHatchLR_Cube_026_Hull_0" geometry={nodes.GearHatchLR_Cube_026_Hull_0.geometry} material={materials.Hull} />
                    </group>
                    <group name="GearHatchLL_Cube_025" position={[216.27, -0.19, -47.95]} rotation={[-0.26, 0, 0]}>
                      <mesh name="GearHatchLL_Cube_025_HullInside_0" geometry={nodes.GearHatchLL_Cube_025_HullInside_0.geometry} material={materials.HullInside} />
                      <mesh name="GearHatchLL_Cube_025_Hull_0" geometry={nodes.GearHatchLL_Cube_025_Hull_0.geometry} material={materials.Hull} />
                    </group>
                    <group name="GearHatchRR_Cube_024" position={[-216.28, -0.19, -47.95]} rotation={[-0.26, 0, 0]}>
                      <mesh name="GearHatchRR_Cube_024_HullInside_0" geometry={nodes.GearHatchRR_Cube_024_HullInside_0.geometry} material={materials.HullInside} />
                      <mesh name="GearHatchRR_Cube_024_Hull_0" geometry={nodes.GearHatchRR_Cube_024_Hull_0.geometry} material={materials.Hull} />
                    </group>
                    <group name="GearWheelsRear_Cube_023" position={[0, -21.13, -115.94]} rotation={[-0.33, 0, 0]}>
                      <mesh name="GearWheelsRear_Cube_023_LandingGear_0" geometry={nodes.GearWheelsRear_Cube_023_LandingGear_0.geometry} material={materials.LandingGear} />
                      <mesh name="GearWheelsRear_Cube_023_Wheel_0" geometry={nodes.GearWheelsRear_Cube_023_Wheel_0.geometry} material={materials.Wheel} />
                    </group>
                    <mesh name="GearPiston_Cube_022_LandingGear_0" geometry={nodes.GearPiston_Cube_022_LandingGear_0.geometry} material={materials.LandingGear} />
                  </group>
                  <group name="Instruments_Cockpit_Cube_000">
                    <mesh name="Instruments_Cockpit_Cube_000_Instruments_0" geometry={nodes.Instruments_Cockpit_Cube_000_Instruments_0.geometry} material={materials.Instruments} />
                  </group>
                  <group name="CanopyOpenable_Cube_019" position={[0, 153.02, 85.92]}>
                    <mesh name="CanopyOpenable_Cube_019_Glass_0" geometry={nodes.CanopyOpenable_Cube_019_Glass_0.geometry} material={materials.Glass} />
                    <mesh name="CanopyOpenable_Cube_019_Canopy_0" geometry={nodes.CanopyOpenable_Cube_019_Canopy_0.geometry} material={materials.Canopy} />
                  </group>
                  <group name="FanR_Cube_018" position={[-200.7, 32.37, 109.51]}>
                    <mesh name="FanR_Cube_018_VTolFan_0" geometry={nodes.FanR_Cube_018_VTolFan_0.geometry} material={materials.VTolFan} />
                  </group>
                  <group name="FanL_Cube_016" position={[200.7, 32.37, 109.51]}>
                    <mesh name="FanL_Cube_016_VTolFan_0" geometry={nodes.FanL_Cube_016_VTolFan_0.geometry} material={materials.VTolFan} />
                  </group>
                  <group name="EngineNozzleR_Cube_015" position={[-58.49, 79.33, -148.82]} rotation={[-0.87, 0.17, 0]}>
                    <mesh name="EngineNozzleR_Cube_015_Black_0" geometry={nodes.EngineNozzleR_Cube_015_Black_0.geometry} material={materials.Black} />
                    <mesh name="EngineNozzleR_Cube_015_Engine_0" geometry={nodes.EngineNozzleR_Cube_015_Engine_0.geometry} material={materials.Engine} />
                  </group>
                  <group name="EngineNozzleL_Cube_013" position={[58.49, 79.33, -148.82]} rotation={[-0.87, -0.17, 0]}>
                    <mesh name="EngineNozzleL_Cube_013_Black_0" geometry={nodes.EngineNozzleL_Cube_013_Black_0.geometry} material={materials.Black} />
                    <mesh name="EngineNozzleL_Cube_013_Engine_0" geometry={nodes.EngineNozzleL_Cube_013_Engine_0.geometry} material={materials.Engine} />
                  </group>
                  <group name="GearFront_Cube_012" position={[0, 42.8, 193.56]} rotation={[-1.48, 0, 0]}>
                    <mesh name="GearFront_Cube_012_LandingGear_0" geometry={nodes.GearFront_Cube_012_LandingGear_0.geometry} material={materials.LandingGear} />
                    <mesh name="GearFront_Cube_012_HullInside_0" geometry={nodes.GearFront_Cube_012_HullInside_0.geometry} material={materials.HullInside} />
                    <mesh name="GearFront_Cube_012_Hull_0" geometry={nodes.GearFront_Cube_012_Hull_0.geometry} material={materials.Hull} />
                    <mesh name="GearFront_Cube_012_Wheel_0" geometry={nodes.GearFront_Cube_012_Wheel_0.geometry} material={materials.Wheel} />
                  </group>
                  <group name="Hatch2_2R_Cube_011" position={[-107.46, 46.13, 108.69]}>
                    <mesh name="Hatch2_2R_Cube_011_HullInside_0" geometry={nodes.Hatch2_2R_Cube_011_HullInside_0.geometry} material={materials.HullInside} />
                    <mesh name="Hatch2_2R_Cube_011_Hull_0" geometry={nodes.Hatch2_2R_Cube_011_Hull_0.geometry} material={materials.Hull} />
                  </group>
                  <group name="Hatch2_2L_Cube_010" position={[108.88, 45.93, 108.69]}>
                    <mesh name="Hatch2_2L_Cube_010_HullInside_0" geometry={nodes.Hatch2_2L_Cube_010_HullInside_0.geometry} material={materials.HullInside} />
                    <mesh name="Hatch2_2L_Cube_010_Hull_0" geometry={nodes.Hatch2_2L_Cube_010_Hull_0.geometry} material={materials.Hull} />
                  </group>
                  <group name="Hatch2R_Cube_009" position={[-102.55, 58.38, 108.88]}>
                    <mesh name="Hatch2R_Cube_009_HullInside_0" geometry={nodes.Hatch2R_Cube_009_HullInside_0.geometry} material={materials.HullInside} />
                    <mesh name="Hatch2R_Cube_009_Hull_0" geometry={nodes.Hatch2R_Cube_009_Hull_0.geometry} material={materials.Hull} />
                  </group>
                  <group name="Hatch2L_Cube_008" position={[101.84, 57.03, 108.88]}>
                    <mesh name="Hatch2L_Cube_008_HullInside_0" geometry={nodes.Hatch2L_Cube_008_HullInside_0.geometry} material={materials.HullInside} />
                    <mesh name="Hatch2L_Cube_008_Hull_0" geometry={nodes.Hatch2L_Cube_008_Hull_0.geometry} material={materials.Hull} />
                  </group>
                  <group name="Hatch1_2R_Cube_006" position={[-294.54, 55.17, 106.39]}>
                    <mesh name="Hatch1_2R_Cube_006_HullInside_0" geometry={nodes.Hatch1_2R_Cube_006_HullInside_0.geometry} material={materials.HullInside} />
                    <mesh name="Hatch1_2R_Cube_006_Hull_0" geometry={nodes.Hatch1_2R_Cube_006_Hull_0.geometry} material={materials.Hull} />
                  </group>
                  <group name="Hatch1_2L_Cube_005" position={[296.77, 56.85, 106.39]}>
                    <mesh name="Hatch1_2L_Cube_005_HullInside_0" geometry={nodes.Hatch1_2L_Cube_005_HullInside_0.geometry} material={materials.HullInside} />
                    <mesh name="Hatch1_2L_Cube_005_Hull_0" geometry={nodes.Hatch1_2L_Cube_005_Hull_0.geometry} material={materials.Hull} />
                  </group>
                  <group name="Hatch1R_Cube_004" position={[-299.39, 57.64, 90.28]}>
                    <mesh name="Hatch1R_Cube_004_HullInside_0" geometry={nodes.Hatch1R_Cube_004_HullInside_0.geometry} material={materials.HullInside} />
                    <mesh name="Hatch1R_Cube_004_Hull_0" geometry={nodes.Hatch1R_Cube_004_Hull_0.geometry} material={materials.Hull} />
                  </group>
                  <group name="Hatch1L_Cube_002" position={[295.11, 60.17, 108.48]}>
                    <mesh name="Hatch1L_Cube_002_HullInside_0" geometry={nodes.Hatch1L_Cube_002_HullInside_0.geometry} material={materials.HullInside} />
                    <mesh name="Hatch1L_Cube_002_Hull_0" geometry={nodes.Hatch1L_Cube_002_Hull_0.geometry} material={materials.Hull} />
                  </group>
                  <group name="Cockpit_Cube_001">
                    <mesh name="Cockpit_Cube_001_SeatStoff_0" geometry={nodes.Cockpit_Cube_001_SeatStoff_0.geometry} material={materials.SeatStoff} />
                    <mesh name="Cockpit_Cube_001_Cockpit_0" geometry={nodes.Cockpit_Cube_001_Cockpit_0.geometry} material={materials.Cockpit} />
                  </group>
                  <group name="Black_Cube_000">
                    <mesh name="Black_Cube_000_Black_0" geometry={nodes.Black_Cube_000_Black_0.geometry} material={materials.Black} />
                  </group>
                  <group name="Glass_Cube_021">
                    <mesh name="Glass_Cube_021_Glass_0" geometry={nodes.Glass_Cube_021_Glass_0.geometry} material={materials.Glass} />
                  </group>
                  <group name="Nemesis_Cube_014">
                    <mesh name="Nemesis_Cube_014_HullInside_0" geometry={nodes.Nemesis_Cube_014_HullInside_0.geometry} material={materials.HullInside} />
                    <mesh name="Nemesis_Cube_014_Hull_0" geometry={nodes.Nemesis_Cube_014_Hull_0.geometry} material={materials.Hull} />
                    <mesh name="Nemesis_Cube_014_Cannon_0" geometry={nodes.Nemesis_Cube_014_Cannon_0.geometry} material={materials.Cannon} />
                    <mesh name="Nemesis_Cube_014_Engine_0" geometry={nodes.Nemesis_Cube_014_Engine_0.geometry} material={materials.Engine} />
                    <mesh name="Nemesis_Cube_014_Canopy_0" geometry={nodes.Nemesis_Cube_014_Canopy_0.geometry} material={materials.Canopy} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/chernovan_nemesis/scene.gltf')
