/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/mafer_city/scene.gltf -t -r public
Author: Mafer Luna (https://sketchfab.com/Fernanda.Aldaco.de.Luna)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mafer-city-2bd53c28a598423f81e883224332dfd1
Title: Mafer_City
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Blimp_Window_0: THREE.Mesh
    Blimp_Blue_building_0: THREE.Mesh
    Blimp_Pink_buildings_0: THREE.Mesh
    Car_Blue_Wheels_0: THREE.Mesh
    Car_Blue_Window_0: THREE.Mesh
    Car_Blue_Grey_material2_0: THREE.Mesh
    Car_Blue_Car_yellow_0: THREE.Mesh
    Car_Blue_White_material2_0: THREE.Mesh
    Car_Green_Wheels_0: THREE.Mesh
    Car_Green_Tree_color3_0: THREE.Mesh
    Car_Green_Grey_material2_0: THREE.Mesh
    Car_Green_Car_yellow_0: THREE.Mesh
    Car_Green_White_material2_0: THREE.Mesh
    Car_Yellow_Wheels_0: THREE.Mesh
    Car_Yellow_Grey_material2_0: THREE.Mesh
    Car_Yellow_Car_yellow_0: THREE.Mesh
    Car_Yellow_White_material2_0: THREE.Mesh
    Hot_air_balloon_Orange_Basket_0: THREE.Mesh
    Hot_air_balloon_Pink_material_0: THREE.Mesh
    Hot_air_balloon_White_material_0: THREE.Mesh
    Wheel_of_fortune_Grey_material2_0: THREE.Mesh
    Wheel_of_fortune_Window_0: THREE.Mesh
    Boat_box__0: THREE.Mesh
    Boat_box2_White_material2_0: THREE.Mesh
    Boat_White_material2_0: THREE.Mesh
    Boat_Blue_building_0: THREE.Mesh
    Boat_Pink_buildings_0: THREE.Mesh
    Boat_Grey_material2_0: THREE.Mesh
    ['Buildings_Material_#552_0']: THREE.Mesh
    Buildings_Cyan_building_0: THREE.Mesh
    Buildings_Window_0: THREE.Mesh
    Buildings_Blue_building2_0: THREE.Mesh
    Buildings_Blue_building_0: THREE.Mesh
    Buildings_Pink_material_0: THREE.Mesh
    Buildings_Blue_building3_0: THREE.Mesh
    Buildings_White_material2_0: THREE.Mesh
    Buildings_Highway_0: THREE.Mesh
    Buildings_Pink_buildings_0: THREE.Mesh
    Buildings_Grey_material2_0: THREE.Mesh
    ['Buildings_Material_#553_0']: THREE.Mesh
    Buildings_Tree_color3_0: THREE.Mesh
    Buildings_Roof_pink_0: THREE.Mesh
    Buildings_White_material_0: THREE.Mesh
    ['Buildings_Material_#3_0']: THREE.Mesh
    Buildings_Sand_0: THREE.Mesh
    Buildings_Grey_material1_0: THREE.Mesh
    ['Buildings_Material_#1192_0']: THREE.Mesh
    Cars_Wheels_0: THREE.Mesh
    Cars_Grey_material2_0: THREE.Mesh
    Cars_Car_red_0: THREE.Mesh
    Cars_White_material2_0: THREE.Mesh
    Cars_Window_0: THREE.Mesh
    Cars_Car_yellow_0: THREE.Mesh
    Cars_Tree_color3_0: THREE.Mesh
    Cars_Blue_building3_0: THREE.Mesh
    Floor_Highway_0: THREE.Mesh
    Floor_White_material2_0: THREE.Mesh
    Floor_Grass_0: THREE.Mesh
    Floor_Grey_material2_0: THREE.Mesh
    Other_White_material2_0: THREE.Mesh
    ['Other_Material_#1419_0']: THREE.Mesh
    ['Other_Material_#1417_0']: THREE.Mesh
    Other_Blue_building_0: THREE.Mesh
    Other_Window_0: THREE.Mesh
    Other_Grey_material2_0: THREE.Mesh
    Other_Grey_material1_0: THREE.Mesh
    Other_Pink_buildings_0: THREE.Mesh
    Other_Cyan_building_0: THREE.Mesh
    Other_Sand_0: THREE.Mesh
    Other_Pink_material_0: THREE.Mesh
    Other_Orange_Basket_0: THREE.Mesh
    Water_Water_0: THREE.Mesh
    Wheel_base_Blue_building_0: THREE.Mesh
    Grass_Grass_0: THREE.Mesh
    Grass_Sand_0: THREE.Mesh
    Trees_Tree_color1_0: THREE.Mesh
    Trees_Wood_0: THREE.Mesh
    Trees_Tree_color3_0: THREE.Mesh
  }
  materials: {
    Window: THREE.MeshStandardMaterial
    Blue_building: THREE.MeshStandardMaterial
    Pink_buildings: THREE.MeshStandardMaterial
    Wheels: THREE.MeshStandardMaterial
    Grey_material2: THREE.MeshStandardMaterial
    Car_yellow: THREE.MeshStandardMaterial
    White_material2: THREE.MeshStandardMaterial
    Tree_color3: THREE.MeshStandardMaterial
    Orange_Basket: THREE.MeshStandardMaterial
    Pink_material: THREE.MeshStandardMaterial
    White_material: THREE.MeshStandardMaterial
    Boat_box__0: THREE.MeshStandardMaterial
    Material_552: THREE.MeshStandardMaterial
    Cyan_building: THREE.MeshStandardMaterial
    Blue_building2: THREE.MeshStandardMaterial
    Blue_building3: THREE.MeshStandardMaterial
    Highway: THREE.MeshStandardMaterial
    Material_553: THREE.MeshStandardMaterial
    Roof_pink: THREE.MeshStandardMaterial
    Material_3: THREE.MeshStandardMaterial
    Sand: THREE.MeshStandardMaterial
    Grey_material1: THREE.MeshStandardMaterial
    Material_1192: THREE.MeshStandardMaterial
    Car_red: THREE.MeshStandardMaterial
    Grass: THREE.MeshStandardMaterial
    Material_1419: THREE.MeshStandardMaterial
    Material_1417: THREE.MeshStandardMaterial
    Water: THREE.MeshStandardMaterial
    Tree_color1: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Main'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/mafer_city/scene.gltf') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="4d883a084ad14d53bf3cc44f237f8a86fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Blimp" position={[8184.43, 31244.31, -26948.42]} rotation={[0, 1.48, 0]}>
                  <mesh name="Blimp_Window_0" geometry={nodes.Blimp_Window_0.geometry} material={materials.Window} />
                  <mesh name="Blimp_Blue_building_0" geometry={nodes.Blimp_Blue_building_0.geometry} material={materials.Blue_building} />
                  <mesh name="Blimp_Pink_buildings_0" geometry={nodes.Blimp_Pink_buildings_0.geometry} material={materials.Pink_buildings} />
                </group>
                <group name="Car_Blue" position={[10878.6, 5249.24, 3013.11]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_39" position={[-38137.96, -4707.78, -1733.08]} rotation={[Math.PI / 2, 0, 0]}>
                    <mesh name="Car_Blue_Wheels_0" geometry={nodes.Car_Blue_Wheels_0.geometry} material={materials.Wheels} />
                    <mesh name="Car_Blue_Window_0" geometry={nodes.Car_Blue_Window_0.geometry} material={materials.Window} />
                    <mesh name="Car_Blue_Grey_material2_0" geometry={nodes.Car_Blue_Grey_material2_0.geometry} material={materials.Grey_material2} />
                    <mesh name="Car_Blue_Car_yellow_0" geometry={nodes.Car_Blue_Car_yellow_0.geometry} material={materials.Car_yellow} />
                    <mesh name="Car_Blue_White_material2_0" geometry={nodes.Car_Blue_White_material2_0.geometry} material={materials.White_material2} />
                  </group>
                </group>
                <group name="Car_Green" position={[37275.28, 5251.07, -3251.51]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_46" position={[7448.79, -38155.3, -1731.91]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                    <mesh name="Car_Green_Wheels_0" geometry={nodes.Car_Green_Wheels_0.geometry} material={materials.Wheels} />
                    <mesh name="Car_Green_Tree_color3_0" geometry={nodes.Car_Green_Tree_color3_0.geometry} material={materials.Tree_color3} />
                    <mesh name="Car_Green_Grey_material2_0" geometry={nodes.Car_Green_Grey_material2_0.geometry} material={materials.Grey_material2} />
                    <mesh name="Car_Green_Car_yellow_0" geometry={nodes.Car_Green_Car_yellow_0.geometry} material={materials.Car_yellow} />
                    <mesh name="Car_Green_White_material2_0" geometry={nodes.Car_Green_White_material2_0.geometry} material={materials.White_material2} />
                  </group>
                </group>
                <group name="Car_Yellow" position={[982.42, 5203.48, -6254.49]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_53" position={[-38156.66, -2120.14, -1682.67]} rotation={[Math.PI / 2, 0, 0]}>
                    <mesh name="Car_Yellow_Wheels_0" geometry={nodes.Car_Yellow_Wheels_0.geometry} material={materials.Wheels} />
                    <mesh name="Car_Yellow_Grey_material2_0" geometry={nodes.Car_Yellow_Grey_material2_0.geometry} material={materials.Grey_material2} />
                    <mesh name="Car_Yellow_Car_yellow_0" geometry={nodes.Car_Yellow_Car_yellow_0.geometry} material={materials.Car_yellow} />
                    <mesh name="Car_Yellow_White_material2_0" geometry={nodes.Car_Yellow_White_material2_0.geometry} material={materials.White_material2} />
                  </group>
                </group>
                <group name="Hot_air_balloon" position={[-7176.89, 11696.89, -23828.65]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Hot_air_balloon_Orange_Basket_0" geometry={nodes.Hot_air_balloon_Orange_Basket_0.geometry} material={materials.Orange_Basket} />
                  <mesh name="Hot_air_balloon_Pink_material_0" geometry={nodes.Hot_air_balloon_Pink_material_0.geometry} material={materials.Pink_material} />
                  <mesh name="Hot_air_balloon_White_material_0" geometry={nodes.Hot_air_balloon_White_material_0.geometry} material={materials.White_material} />
                </group>
                <group name="Wheel_of_fortune" position={[28070.95, 10103.54, 10031.88]} rotation={[-Math.PI / 2, -0.39, 0]}>
                  <group name="Object_98" position={[494.88, -645.21, 1220.48]} rotation={[Math.PI / 2, 0, -0.39]} scale={1.19}>
                    <mesh name="Wheel_of_fortune_Grey_material2_0" geometry={nodes.Wheel_of_fortune_Grey_material2_0.geometry} material={materials.Grey_material2} />
                    <mesh name="Wheel_of_fortune_Window_0" geometry={nodes.Wheel_of_fortune_Window_0.geometry} material={materials.Window} />
                  </group>
                </group>
                <group name="Boat" position={[-12231.13, 3183.01, 27908.57]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Boat_box" position={[-2.95, 2057.87, 1714.86]}>
                    <mesh name="Boat_box__0" geometry={nodes.Boat_box__0.geometry} material={materials.Boat_box__0} />
                  </group>
                  <group name="Boat_box2" position={[-2.95, 4397.57, 1714.86]}>
                    <mesh name="Boat_box2_White_material2_0" geometry={nodes.Boat_box2_White_material2_0.geometry} material={materials.White_material2} />
                  </group>
                  <mesh name="Boat_White_material2_0" geometry={nodes.Boat_White_material2_0.geometry} material={materials.White_material2} />
                  <mesh name="Boat_Blue_building_0" geometry={nodes.Boat_Blue_building_0.geometry} material={materials.Blue_building} />
                  <mesh name="Boat_Pink_buildings_0" geometry={nodes.Boat_Pink_buildings_0.geometry} material={materials.Pink_buildings} />
                  <mesh name="Boat_Grey_material2_0" geometry={nodes.Boat_Grey_material2_0.geometry} material={materials.Grey_material2} />
                </group>
                <group name="Buildings" position={[8731.21, 7669.08, 213.53]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_18" position={[-4635.32, 4603.44, -2118.76]}>
                    <mesh name="Buildings_Material_#552_0" geometry={nodes['Buildings_Material_#552_0'].geometry} material={materials.Material_552} />
                    <mesh name="Buildings_Cyan_building_0" geometry={nodes.Buildings_Cyan_building_0.geometry} material={materials.Cyan_building} />
                    <mesh name="Buildings_Window_0" geometry={nodes.Buildings_Window_0.geometry} material={materials.Window} />
                    <mesh name="Buildings_Blue_building2_0" geometry={nodes.Buildings_Blue_building2_0.geometry} material={materials.Blue_building2} />
                    <mesh name="Buildings_Blue_building_0" geometry={nodes.Buildings_Blue_building_0.geometry} material={materials.Blue_building} />
                    <mesh name="Buildings_Pink_material_0" geometry={nodes.Buildings_Pink_material_0.geometry} material={materials.Pink_material} />
                    <mesh name="Buildings_Blue_building3_0" geometry={nodes.Buildings_Blue_building3_0.geometry} material={materials.Blue_building3} />
                    <mesh name="Buildings_White_material2_0" geometry={nodes.Buildings_White_material2_0.geometry} material={materials.White_material2} />
                    <mesh name="Buildings_Highway_0" geometry={nodes.Buildings_Highway_0.geometry} material={materials.Highway} />
                    <mesh name="Buildings_Pink_buildings_0" geometry={nodes.Buildings_Pink_buildings_0.geometry} material={materials.Pink_buildings} />
                    <mesh name="Buildings_Grey_material2_0" geometry={nodes.Buildings_Grey_material2_0.geometry} material={materials.Grey_material2} />
                    <mesh name="Buildings_Material_#553_0" geometry={nodes['Buildings_Material_#553_0'].geometry} material={materials.Material_553} />
                    <mesh name="Buildings_Tree_color3_0" geometry={nodes.Buildings_Tree_color3_0.geometry} material={materials.Tree_color3} />
                    <mesh name="Buildings_Roof_pink_0" geometry={nodes.Buildings_Roof_pink_0.geometry} material={materials.Roof_pink} />
                    <mesh name="Buildings_White_material_0" geometry={nodes.Buildings_White_material_0.geometry} material={materials.White_material} />
                    <mesh name="Buildings_Material_#3_0" geometry={nodes['Buildings_Material_#3_0'].geometry} material={materials.Material_3} />
                    <mesh name="Buildings_Sand_0" geometry={nodes.Buildings_Sand_0.geometry} material={materials.Sand} />
                    <mesh name="Buildings_Grey_material1_0" geometry={nodes.Buildings_Grey_material1_0.geometry} material={materials.Grey_material1} />
                    <mesh name="Buildings_Material_#1192_0" geometry={nodes['Buildings_Material_#1192_0'].geometry} material={materials.Material_1192} />
                  </group>
                </group>
                <group name="Cars" position={[-19715.09, 5251.61, -21219.07]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_59" position={[38194.3, -579.42, -1729.81]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                    <mesh name="Cars_Wheels_0" geometry={nodes.Cars_Wheels_0.geometry} material={materials.Wheels} />
                    <mesh name="Cars_Grey_material2_0" geometry={nodes.Cars_Grey_material2_0.geometry} material={materials.Grey_material2} />
                    <mesh name="Cars_Car_red_0" geometry={nodes.Cars_Car_red_0.geometry} material={materials.Car_red} />
                    <mesh name="Cars_White_material2_0" geometry={nodes.Cars_White_material2_0.geometry} material={materials.White_material2} />
                    <mesh name="Cars_Window_0" geometry={nodes.Cars_Window_0.geometry} material={materials.Window} />
                    <mesh name="Cars_Car_yellow_0" geometry={nodes.Cars_Car_yellow_0.geometry} material={materials.Car_yellow} />
                    <mesh name="Cars_Tree_color3_0" geometry={nodes.Cars_Tree_color3_0.geometry} material={materials.Tree_color3} />
                    <mesh name="Cars_Blue_building3_0" geometry={nodes.Cars_Blue_building3_0.geometry} material={materials.Blue_building3} />
                  </group>
                </group>
                <group name="Floor" position={[15628.68, 4790.77, 6184.27]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_69" position={[-27298.21, 1255.01, 0]}>
                    <mesh name="Floor_Highway_0" geometry={nodes.Floor_Highway_0.geometry} material={materials.Highway} />
                    <mesh name="Floor_White_material2_0" geometry={nodes.Floor_White_material2_0.geometry} material={materials.White_material2} />
                    <mesh name="Floor_Grass_0" geometry={nodes.Floor_Grass_0.geometry} material={materials.Grass} />
                    <mesh name="Floor_Grey_material2_0" geometry={nodes.Floor_Grey_material2_0.geometry} material={materials.Grey_material2} />
                  </group>
                </group>
                <group name="Other" position={[-5787.9, 7418.4, 380.53]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_79" rotation={[Math.PI / 2, -Math.PI / 6, 0]}>
                    <mesh name="Other_White_material2_0" geometry={nodes.Other_White_material2_0.geometry} material={materials.White_material2} />
                    <mesh name="Other_Material_#1419_0" geometry={nodes['Other_Material_#1419_0'].geometry} material={materials.Material_1419} />
                    <mesh name="Other_Material_#1417_0" geometry={nodes['Other_Material_#1417_0'].geometry} material={materials.Material_1417} />
                    <mesh name="Other_Blue_building_0" geometry={nodes.Other_Blue_building_0.geometry} material={materials.Blue_building} />
                    <mesh name="Other_Window_0" geometry={nodes.Other_Window_0.geometry} material={materials.Window} />
                    <mesh name="Other_Grey_material2_0" geometry={nodes.Other_Grey_material2_0.geometry} material={materials.Grey_material2} />
                    <mesh name="Other_Grey_material1_0" geometry={nodes.Other_Grey_material1_0.geometry} material={materials.Grey_material1} />
                    <mesh name="Other_Pink_buildings_0" geometry={nodes.Other_Pink_buildings_0.geometry} material={materials.Pink_buildings} />
                    <mesh name="Other_Cyan_building_0" geometry={nodes.Other_Cyan_building_0.geometry} material={materials.Cyan_building} />
                    <mesh name="Other_Sand_0" geometry={nodes.Other_Sand_0.geometry} material={materials.Sand} />
                    <mesh name="Other_Pink_material_0" geometry={nodes.Other_Pink_material_0.geometry} material={materials.Pink_material} />
                    <mesh name="Other_Orange_Basket_0" geometry={nodes.Other_Orange_Basket_0.geometry} material={materials.Orange_Basket} />
                  </group>
                </group>
                <group name="Water" position={[-2265.11, 368.08, 715.57]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Water_Water_0" geometry={nodes.Water_Water_0.geometry} material={materials.Water} />
                </group>
                <group name="Wheel_base" position={[28070.95, 11420.54, 10677.1]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_95" rotation={[Math.PI / 2, 0, 0]} scale={1.19}>
                    <mesh name="Wheel_base_Blue_building_0" geometry={nodes.Wheel_base_Blue_building_0.geometry} material={materials.Blue_building} />
                  </group>
                </group>
                <group name="Grass" position={[15628.68, 4790.77, 6184.27]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_102" position={[-27298.21, 1255.01, 0]}>
                    <mesh name="Grass_Grass_0" geometry={nodes.Grass_Grass_0.geometry} material={materials.Grass} />
                    <mesh name="Grass_Sand_0" geometry={nodes.Grass_Sand_0.geometry} material={materials.Sand} />
                  </group>
                </group>
                <group name="Trees" position={[30694.03, 8240.21, 20383.4]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_106" position={[-34936.11, -5218.21, 2246.47]} scale={[1, 1, 0.61]}>
                    <mesh name="Trees_Tree_color1_0" geometry={nodes.Trees_Tree_color1_0.geometry} material={materials.Tree_color1} />
                    <mesh name="Trees_Wood_0" geometry={nodes.Trees_Wood_0.geometry} material={materials.Wood} />
                    <mesh name="Trees_Tree_color3_0" geometry={nodes.Trees_Tree_color3_0.geometry} material={materials.Tree_color3} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mafer_city/scene.gltf')
